print("Hello World")
print("My favourite food is ice cream")
print("My birthday is 27 July")
print("My name is Gwen")
print("I am ")
print("I am learning coding at computhink")
print("If I had $+2000 as a reward, I would buy")