print("Hello from lesson 1")
print ("6 Jan")
print("2025")
print(2025)
print("Bye, end of class")
print("My wallet has $,100,"$")
print("Hello World")
print("My favourite food is ice cream")
print("My birthday is 27 July")
print("My name is Gwen")
print("I am ")
print("I am learning coding at computhink")
print("If I had $+2000 as a reward, I would buy ")
print("Pour milk and cereal into a bowl.")
print("Wake up and get out of bed.")
print("Eat your breakfast.")
print("Hello and how are you?")
print("What is wrong with this")
print("Why is this not working?")
print("Why is this not working?")